//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "conversations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub kind: String,
    pub name: Option<String>,
    #[sea_orm(unique_key = "dm_key")]
    pub dm_key: Option<String>,
    #[sea_orm(unique_key = "dm_key")]
    pub organisation_id: i64,
    pub created_by_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::conversation_members::Entity")]
    ConversationMembers,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(
        belongs_to = "super::organisations::Entity",
        from = "Column::OrganisationId",
        to = "super::organisations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organisations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::conversation_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConversationMembers.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::organisations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organisations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
