//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "meetings")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    pub held_on: Date,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "Text")]
    pub decisions: String,
    pub organisation_id: i64,
    pub created_by_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::meeting_attendees::Entity")]
    MeetingAttendees,
    #[sea_orm(
        belongs_to = "super::organisations::Entity",
        from = "Column::OrganisationId",
        to = "super::organisations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organisations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::meeting_attendees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MeetingAttendees.def()
    }
}

impl Related<super::organisations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organisations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
