//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod conversation_members;
pub mod conversations;
pub mod meeting_attendees;
pub mod meetings;
pub mod memberships;
pub mod messages;
pub mod notifications;
pub mod organisations;
pub mod projects;
pub mod saved_views;
pub mod task_assignees;
pub mod task_notes;
pub mod tasks;
pub mod users;
