//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notifications")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub link: String,
    pub read_at: Option<DateTimeWithTimeZone>,
    pub organisation_id: i64,
    pub user_id: i64,
    pub actor_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organisations::Entity",
        from = "Column::OrganisationId",
        to = "super::organisations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organisations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ActorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users1,
}

impl Related<super::organisations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organisations.def()
    }
}
