//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub lane: String,
    pub status: String,
    pub progress: i64,
    pub accent: String,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    pub sort_order: i64,
    pub organisation_id: i64,
    pub owner_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organisations::Entity",
        from = "Column::OrganisationId",
        to = "super::organisations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organisations,
    #[sea_orm(has_many = "super::tasks::Entity")]
    Tasks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::organisations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organisations.def()
    }
}

impl Related<super::tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tasks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
